### ISSUE TITLE
add upload SRT file function

### ISSUE THREAD

**Issue by billyphuse** [ethicnology/charabia#1]
Because I have 878 lines of subtitles,  
Copy and paste 878 lines of subtitles can't process now

**Comment by ethicnology** [comment]
@billyphuse I used it myself with more than 2k lines of subtitles many times…

I think you have another issue probably linked to your input.
When SRT mode is selected, I'm making several checks to ensure that the SRT format is valid

valid:
```txt
1
00:01:27,960 --> 00:01:29,999
(Pauline) What's with the gross smell?

2
00:01:30,646 --> 00:01:33,765
- It's incense. My gradma's used to smell like that.

3
00:01:39,534 --> 00:01:40,645
Great.
```

invalid:
```txt
4
00:01:27,960 --> 00:01:29,999
(Pauline) What's with the gross smell?

5
00:01:30,646 --> 00:01:33,765
- It's incense. My gradma's used to smell like that.

6
00:01:39,534 --> 00:01:40,645
Great.
```
